name: Create PowerShell modules from script files

on:
  workflow_dispatch:
  push:
    branches:
      - 'develop'
    paths:
      - 'scripts/*'

jobs:
  create_modules:
    name: Create Modules
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      statuses: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Run script
        if: success()
        shell: pwsh
        run: |
          ./modules/CreateModules.ps1

      - name: Push created module back to repo
        if: success()
        uses: EndBug/add-and-commit@v9
