name: Lint workflows
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - 'release/*'

jobs:
  lint_workflows:
    name: Lint Workflows
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cschleiden/actions-linter@v1
        with:
          workflows: '[".github/workflows/*.yml"]'
