name: Validate GitHub Actions Workflows

on:
  workflow_dispatch:
  push:
    branches:
      - 'feature/*'
  pull_request:
    branches:
      - main
      - 'release/*'

jobs:
  lint_workflows:
    name: Lint Workflows
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Action Linting
        uses: cfy9/action-linting@main
        with:
          additional_arguments: "-color"
